// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMIwKp7C8q0Ihbks9dyOEVh8-PlKEYfOs',
    appId: '1:209657576394:web:61424ab29fb284cb7fed33',
    messagingSenderId: '209657576394',
    projectId: 'flutter-app-f48fe',
    authDomain: 'flutter-app-f48fe.firebaseapp.com',
    storageBucket: 'flutter-app-f48fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZVe0KTYmQFrPuYOc45-DXlK_vLQINwo',
    appId: '1:209657576394:android:ae05157f85456f257fed33',
    messagingSenderId: '209657576394',
    projectId: 'flutter-app-f48fe',
    storageBucket: 'flutter-app-f48fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMIwKp7C8q0Ihbks9dyOEVh8-PlKEYfOs',
    appId: '1:209657576394:web:50042178e8fb7b167fed33',
    messagingSenderId: '209657576394',
    projectId: 'flutter-app-f48fe',
    authDomain: 'flutter-app-f48fe.firebaseapp.com',
    storageBucket: 'flutter-app-f48fe.firebasestorage.app',
  );
}
